In [17]:
import torch

<p> requires_grad=Trueをつけることによって、微分対象のtensorを指定できる。
requires_grad = Falseはfinetuningでの層のパラメータの固定をしたいときなどに使う。requires_grad=Trueなどの引数を使用して行列の加算などをすると、計算グラフが構築される。なので下記のx,yは加算された時点で内部的にはつながっている。そして加算された結果(y)ではgrad_fnという属性を持つ。これはどのFunctionによって生成されたtensorなのかを参照ができる。ただの変数にgrad_fnを指定するとNoneが返ってくる。今回のyでは加算された結果が入っているのでAddが参照される。
</p>

In [18]:
x = torch.ones(2, 2,requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [19]:
"""ここではyはrequired_gradを引数とするxから結果を引き継いでいるので、
#zはgrad_fnの属性を持っている"""
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [20]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
"""requires_gradは指定されていないので
計算グラフは構築されないが下記のやり方で構築を可能にする。"""
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


<h3>勾配</h3>

$out = \frac{1}{4}\sum_{i}z_i,z_i = 3(x_i+2)^2$<-これがoutの計算<br>
xが今
\begin{pmatrix}
1 & 1 \\
1 & 1 \\
\end{pmatrix}
であるから
$\frac{dz_i}{dx_i} = 6x_i+12$ より<br>
$ \frac{dout}{dx_i} = \frac{3}{2}(x_i +2 )$でxの勾配を求める(要素がすべて1の行列であるから)からx = 1で計算をして
\begin{pmatrix}
4.5 & 4.5 \\
4.5 & 4.5 \\
\end{pmatrix}

In [21]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
