In [1]:
from __future__ import print_function
import torch
import numpy as np

<p>何かしらの値が入る(not initialized,実行のたびにかわる)</p>

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39]])


<p>何かしらの値が入る(random initialized,実行のたびにかわる $0<x<1?$)</p>

In [16]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6250, 0.1520, 0.7480],
        [0.2037, 0.3160, 0.5314],
        [0.1090, 0.6828, 0.7686],
        [0.2870, 0.3595, 0.1048],
        [0.8464, 0.7757, 0.4505]])


<p>0の行列(np.zeros)</p>

In [17]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<p>np.array</p>

In [18]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


<p>上で定義されていたものを変える</p

In [24]:
# 行列xを1で埋める（double型）
x = x.new_ones(5, 3, dtype=torch.long)
print(x)
# 行列xを平均0，分散1の正規分布で埋める（float型）
# このように型の上書きもできる
x = torch.randn_like(x, dtype=torch.float)
print(x)   

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[ 0.9650,  0.0569,  0.5698],
        [ 0.2651,  0.1623, -0.4595],
        [ 1.7692, -0.2797,  1.4178],
        [ 1.4159,  0.2958,  0.5647],
        [ 1.1038, -0.0021, -0.9707]])


<p>?.shape()</p>

In [26]:
print(x.size())

torch.Size([5, 3])


<p>行列同士の加算</p>

In [38]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.9650,  0.0569,  0.5698],
        [ 0.2651,  0.1623, -0.4595],
        [ 1.7692, -0.2797,  1.4178],
        [ 1.4159,  0.2958,  0.5647],
        [ 1.1038, -0.0021, -0.9707]])
tensor([[0.8076, 0.9392, 0.4408],
        [0.8998, 0.4395, 0.3493],
        [0.1738, 0.9196, 0.0626],
        [0.3677, 0.2678, 0.9594],
        [0.8003, 0.6209, 0.6020]])
tensor([[ 1.7726,  0.9961,  1.0106],
        [ 1.1649,  0.6019, -0.1101],
        [ 1.9429,  0.6399,  1.4804],
        [ 1.7836,  0.5636,  1.5241],
        [ 1.9042,  0.6188, -0.3687]])


In [39]:
print(torch.add(x, y))

tensor([[ 1.7726,  0.9961,  1.0106],
        [ 1.1649,  0.6019, -0.1101],
        [ 1.9429,  0.6399,  1.4804],
        [ 1.7836,  0.5636,  1.5241],
        [ 1.9042,  0.6188, -0.3687]])


In [40]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7726,  0.9961,  1.0106],
        [ 1.1649,  0.6019, -0.1101],
        [ 1.9429,  0.6399,  1.4804],
        [ 1.7836,  0.5636,  1.5241],
        [ 1.9042,  0.6188, -0.3687]])


<p>resultという箱を最初に定義しておいて計算結果をそこに入れる計算結果の結果の形を与えておかなければならないが、自動的に変えてくれる。</p>

In [37]:
result = torch.empty(5, 4)
print(result.size())
torch.add(x, y, out=result)
print(result.size())
print(result)

torch.Size([5, 4])
torch.Size([5, 3])
tensor([[ 1.0655,  0.8380,  0.6673],
        [ 0.6685,  0.7221, -0.3826],
        [ 2.6350,  0.3643,  2.2662],
        [ 1.4569,  1.2873,  0.6913],
        [ 1.9184,  0.5826, -0.6012]])


<p>行列一列などの取り出し</p>

In [44]:
print(x)
print(x[:, 0])
print(x[:, 1])
print(x[:, 2])

tensor([[ 0.9650,  0.0569,  0.5698],
        [ 0.2651,  0.1623, -0.4595],
        [ 1.7692, -0.2797,  1.4178],
        [ 1.4159,  0.2958,  0.5647],
        [ 1.1038, -0.0021, -0.9707]])
tensor([0.9650, 0.2651, 1.7692, 1.4159, 1.1038])
tensor([ 0.0569,  0.1623, -0.2797,  0.2958, -0.0021])
tensor([ 0.5698, -0.4595,  1.4178,  0.5647, -0.9707])


<p>リサイズ</p>

In [47]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.2584,  1.0276, -0.1553, -0.3815],
        [ 0.2134,  0.1717, -0.9681,  2.0915],
        [ 2.4776,  0.2967,  0.0885, -0.9251],
        [ 0.5808, -2.0552, -1.0990,  1.5134]])
tensor([ 1.2584,  1.0276, -0.1553, -0.3815,  0.2134,  0.1717, -0.9681,  2.0915,
         2.4776,  0.2967,  0.0885, -0.9251,  0.5808, -2.0552, -1.0990,  1.5134])
tensor([[ 1.2584,  1.0276, -0.1553, -0.3815,  0.2134,  0.1717, -0.9681,  2.0915],
        [ 2.4776,  0.2967,  0.0885, -0.9251,  0.5808, -2.0552, -1.0990,  1.5134]])


<p>要素<strong>一つ</strong>だけの取り出し</p>

In [50]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.2229])
-2.222933530807495


<p>GPUがあったら起動する</p>

In [51]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-1.2229], device='cuda:0')
tensor([-1.2229], dtype=torch.float64)
